// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DynamoDBRepository is an autogenerated mock type for the DynamoDBRepository type
type DynamoDBRepository struct {
	mock.Mock
}

// StoreResult provides a mock function with given fields: ctx, id, version, result
func (_m *DynamoDBRepository) StoreResult(ctx context.Context, id string, version int, result interface{}) error {
	ret := _m.Called(ctx, id, version, result)

	if len(ret) == 0 {
		panic("no return value specified for StoreResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, interface{}) error); ok {
		r0 = rf(ctx, id, version, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDynamoDBRepository creates a new instance of DynamoDBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoDBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoDBRepository {
	mock := &DynamoDBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
