// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/pablodev/s3-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// S3Repository is an autogenerated mock type for the S3Repository type
type S3Repository struct {
	mock.Mock
}

// DownloadAllYaml provides a mock function with given fields: ctx
func (_m *S3Repository) DownloadAllYaml(ctx context.Context) ([]entity.YamlFile, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DownloadAllYaml")
	}

	var r0 []entity.YamlFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.YamlFile, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.YamlFile); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.YamlFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadYaml provides a mock function with given fields: ctx, file
func (_m *S3Repository) UploadYaml(ctx context.Context, file entity.YamlFile) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadYaml")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.YamlFile) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewS3Repository creates a new instance of S3Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Repository(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Repository {
	mock := &S3Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
