// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DynamoDBRepository is an autogenerated mock type for the DynamoDBRepository type
type DynamoDBRepository struct {
	mock.Mock
}

type DynamoDBRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamoDBRepository) EXPECT() *DynamoDBRepository_Expecter {
	return &DynamoDBRepository_Expecter{mock: &_m.Mock}
}

// StoreResult provides a mock function with given fields: ctx, id, version, result
func (_m *DynamoDBRepository) StoreResult(ctx context.Context, id string, version int, result interface{}) error {
	ret := _m.Called(ctx, id, version, result)

	if len(ret) == 0 {
		panic("no return value specified for StoreResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, interface{}) error); ok {
		r0 = rf(ctx, id, version, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DynamoDBRepository_StoreResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreResult'
type DynamoDBRepository_StoreResult_Call struct {
	*mock.Call
}

// StoreResult is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - version int
//   - result interface{}
func (_e *DynamoDBRepository_Expecter) StoreResult(ctx interface{}, id interface{}, version interface{}, result interface{}) *DynamoDBRepository_StoreResult_Call {
	return &DynamoDBRepository_StoreResult_Call{Call: _e.mock.On("StoreResult", ctx, id, version, result)}
}

func (_c *DynamoDBRepository_StoreResult_Call) Run(run func(ctx context.Context, id string, version int, result interface{})) *DynamoDBRepository_StoreResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(interface{}))
	})
	return _c
}

func (_c *DynamoDBRepository_StoreResult_Call) Return(_a0 error) *DynamoDBRepository_StoreResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DynamoDBRepository_StoreResult_Call) RunAndReturn(run func(context.Context, string, int, interface{}) error) *DynamoDBRepository_StoreResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewDynamoDBRepository creates a new instance of DynamoDBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoDBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoDBRepository {
	mock := &DynamoDBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
