// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/pablodev/s3-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// S3Repository is an autogenerated mock type for the S3Repository type
type S3Repository struct {
	mock.Mock
}

type S3Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Repository) EXPECT() *S3Repository_Expecter {
	return &S3Repository_Expecter{mock: &_m.Mock}
}

// DownloadAllYaml provides a mock function with given fields: ctx
func (_m *S3Repository) DownloadAllYaml(ctx context.Context) ([]entity.YamlFile, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DownloadAllYaml")
	}

	var r0 []entity.YamlFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.YamlFile, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.YamlFile); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.YamlFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// S3Repository_DownloadAllYaml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAllYaml'
type S3Repository_DownloadAllYaml_Call struct {
	*mock.Call
}

// DownloadAllYaml is a helper method to define mock.On call
//   - ctx context.Context
func (_e *S3Repository_Expecter) DownloadAllYaml(ctx interface{}) *S3Repository_DownloadAllYaml_Call {
	return &S3Repository_DownloadAllYaml_Call{Call: _e.mock.On("DownloadAllYaml", ctx)}
}

func (_c *S3Repository_DownloadAllYaml_Call) Run(run func(ctx context.Context)) *S3Repository_DownloadAllYaml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *S3Repository_DownloadAllYaml_Call) Return(_a0 []entity.YamlFile, _a1 error) *S3Repository_DownloadAllYaml_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *S3Repository_DownloadAllYaml_Call) RunAndReturn(run func(context.Context) ([]entity.YamlFile, error)) *S3Repository_DownloadAllYaml_Call {
	_c.Call.Return(run)
	return _c
}

// UploadYaml provides a mock function with given fields: ctx, file
func (_m *S3Repository) UploadYaml(ctx context.Context, file entity.YamlFile) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadYaml")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.YamlFile) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// S3Repository_UploadYaml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadYaml'
type S3Repository_UploadYaml_Call struct {
	*mock.Call
}

// UploadYaml is a helper method to define mock.On call
//   - ctx context.Context
//   - file entity.YamlFile
func (_e *S3Repository_Expecter) UploadYaml(ctx interface{}, file interface{}) *S3Repository_UploadYaml_Call {
	return &S3Repository_UploadYaml_Call{Call: _e.mock.On("UploadYaml", ctx, file)}
}

func (_c *S3Repository_UploadYaml_Call) Run(run func(ctx context.Context, file entity.YamlFile)) *S3Repository_UploadYaml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.YamlFile))
	})
	return _c
}

func (_c *S3Repository_UploadYaml_Call) Return(_a0 error) *S3Repository_UploadYaml_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *S3Repository_UploadYaml_Call) RunAndReturn(run func(context.Context, entity.YamlFile) error) *S3Repository_UploadYaml_Call {
	_c.Call.Return(run)
	return _c
}

// NewS3Repository creates a new instance of S3Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Repository(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Repository {
	mock := &S3Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
