// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/pablodev/s3-test/internal/adapter/repository"
	"github.com/pablodev/s3-test/internal/driver"
	"github.com/pablodev/s3-test/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*usecase.StorageUseCase, error) {
	string2 := _wireStringValue
	config, err := LoadConfig(string2)
	if err != nil {
		return nil, err
	}
	awsConfig, err := ProvideAWSConfig(ctx, config)
	if err != nil {
		return nil, err
	}
	s3Driver := driver.NewS3Driver(awsConfig, string2)
	dynamoDBDriver := driver.NewDynamoDBDriver(awsConfig, string2)
	storageUseCase := usecase.NewStorageUseCase(s3Driver, dynamoDBDriver)
	return storageUseCase, nil
}

var (
	_wireStringValue = "config.local.yaml"
)

// wire.go:

var superSet = wire.NewSet(
	LoadConfig,
	ProvideAWSConfig,
	ProvideS3Bucket,
	ProvideDynamoDBTable, driver.NewS3Driver, driver.NewDynamoDBDriver, wire.Bind(new(repository.S3Repository), new(*driver.S3Driver)), wire.Bind(new(repository.DynamoDBRepository), new(*driver.DynamoDBDriver)), usecase.NewStorageUseCase,
)
