// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/pablodev/s3-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CustomDomainRepository is an autogenerated mock type for the CustomDomainRepository type
type CustomDomainRepository struct {
	mock.Mock
}

type CustomDomainRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomDomainRepository) EXPECT() *CustomDomainRepository_Expecter {
	return &CustomDomainRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: id
func (_m *CustomDomainRepository) GetByID(id string) (*entity.CustomDomain, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.CustomDomain
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.CustomDomain, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.CustomDomain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CustomDomain)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomDomainRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CustomDomainRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *CustomDomainRepository_Expecter) GetByID(id interface{}) *CustomDomainRepository_GetByID_Call {
	return &CustomDomainRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *CustomDomainRepository_GetByID_Call) Run(run func(id string)) *CustomDomainRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CustomDomainRepository_GetByID_Call) Return(_a0 *entity.CustomDomain, _a1 error) *CustomDomainRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomDomainRepository_GetByID_Call) RunAndReturn(run func(string) (*entity.CustomDomain, error)) *CustomDomainRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: domain
func (_m *CustomDomainRepository) Save(domain *entity.CustomDomain) error {
	ret := _m.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.CustomDomain) error); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomDomainRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CustomDomainRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - domain *entity.CustomDomain
func (_e *CustomDomainRepository_Expecter) Save(domain interface{}) *CustomDomainRepository_Save_Call {
	return &CustomDomainRepository_Save_Call{Call: _e.mock.On("Save", domain)}
}

func (_c *CustomDomainRepository_Save_Call) Run(run func(domain *entity.CustomDomain)) *CustomDomainRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.CustomDomain))
	})
	return _c
}

func (_c *CustomDomainRepository_Save_Call) Return(_a0 error) *CustomDomainRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomDomainRepository_Save_Call) RunAndReturn(run func(*entity.CustomDomain) error) *CustomDomainRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomDomainRepository creates a new instance of CustomDomainRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomDomainRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomDomainRepository {
	mock := &CustomDomainRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
